# chmod +x clean.sh ; clean.sh
tdir=trash/
if [ ! -d $tdir ]; then echo "Creating dir $tdir"; mkdir $tdir; fi

#What follows are mv, rm, and other commands to "clean" up unwanted files
# that are generated by some application
rm -f *~
mv All_*.csv $tdir
mv th*.csv $tdir
mv TMP_*.txt $tdir

#Warning, the folling dirs may contain valuable results! 
#mv q*_zscan/ $tdir